"""
IVR Client - WebSocket Audio Streaming for Telephonic IVR System

This module implements the client-side logic for streaming audio to a Colab server
running Faster-Whisper, receiving transcription/intent data, and processing it
through an LLM orchestrator.
"""

import asyncio
import websockets
import json
import wave
import time
import os
import logging
from typing import Optional, Dict, Any
from .ivr_orchestrator import IVROrchestrator

logger = logging.getLogger(__name__)

# Configuration
# Replace this with the ngrok URL generated by your Colab notebook
COLAB_WEBSOCKET_URL = "ws://YOUR_NGROK_URL.ngrok.app/stream"
TEST_AUDIO_FILE = "test_hindi_complaint.wav"


async def mock_llm_processing(pipeline_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    This function simulates passing the Colab pipeline data to your LLM (e.g., Claude/Opus API)
    using the system prompt defined in ivr_prompts.py.

    Args:
        pipeline_data: Data from the Colab processing pipeline containing:
            - text/raw_text: Transcribed speech
            - language: Detected language
            - detected_profile: Regional accent profile
            - intent_data: Intent classification

    Returns:
        LLM response formatted for TTS
    """
    print("\n--- Sending data to Orchestrator LLM ---")
    print(f"Context provided to LLM: {json.dumps(pipeline_data, indent=2)}")

    # Initialize the IVR orchestrator
    orchestrator = IVROrchestrator()

    # Process the pipeline data through the orchestrator
    llm_response = await orchestrator.process_pipeline_data(pipeline_data)

    print("\n--- LLM Output (Ready for TTS) ---")
    print(json.dumps(llm_response, indent=2))

    return llm_response


async def stream_audio_to_pipeline(
    websocket_url: Optional[str] = None,
    audio_file: Optional[str] = None
) -> None:
    """
    Acts as the Asterisk/AGI client. Reads a local audio file and streams it
    to the Colab WebSocket server in chunks, exactly like a live phone call.

    Args:
        websocket_url: URL of the Colab WebSocket server (defaults to COLAB_WEBSOCKET_URL)
        audio_file: Path to the test audio file (defaults to TEST_AUDIO_FILE)

    Raises:
        FileNotFoundError: If the audio file doesn't exist
        websockets.exceptions.WebSocketException: If connection fails
    """
    ws_url = websocket_url or COLAB_WEBSOCKET_URL
    audio_path = audio_file or TEST_AUDIO_FILE

    if not os.path.exists(audio_path):
        error_msg = (
            f"Error: Please place a 16kHz, 16-bit Mono WAV file named '{audio_path}' "
            "in this directory."
        )
        print(error_msg)
        raise FileNotFoundError(error_msg)

    try:
        async with websockets.connect(ws_url) as websocket:
            print(f"Connected to Unified Pipeline: {ws_url}")

            with wave.open(audio_path, 'rb') as wf:
                # Verify audio format (must match Asterisk's 8kHz or 16kHz raw PCM)
                framerate = wf.getframerate()
                channels = wf.getnchannels()
                sampwidth = wf.getsampwidth()

                print(f"Streaming audio: {framerate}Hz, {channels} channel(s), "
                      f"{sampwidth*8}-bit")

                if channels != 1:
                    logger.warning(f"Audio has {channels} channels, expected 1 (mono)")

                # Stream chunks of audio (e.g., 4000 frames at a time)
                chunk_size = 4000
                data = wf.readframes(chunk_size)

                while data:
                    # 1. Send raw bytes to Colab
                    await websocket.send(data)

                    # 2. Briefly wait to simulate real-time talking speed
                    await asyncio.sleep(chunk_size / framerate)

                    # 3. Check if Colab has sent back a transcription/intent packet
                    try:
                        # Non-blocking receive
                        response = await asyncio.wait_for(websocket.recv(), timeout=0.1)
                        pipeline_data = json.loads(response)

                        print("\n[✔] Pipeline Processed a Chunk!")
                        print(f"User Said: {pipeline_data.get('text', pipeline_data.get('raw_text'))}")

                        detected_profile = pipeline_data.get('detected_profile', {})
                        if isinstance(detected_profile, dict):
                            print(f"Detected Profile: {detected_profile.get('lang', 'unknown')}")
                        else:
                            print(f"Detected Profile: {detected_profile}")

                        # 4. Trigger the LLM with the extracted data
                        await mock_llm_processing(pipeline_data)

                    except asyncio.TimeoutError:
                        # No response yet, keep sending audio
                        pass
                    except json.JSONDecodeError as e:
                        logger.error(f"Failed to decode JSON response: {e}")

                    data = wf.readframes(chunk_size)

            print("\nFinished streaming audio file.")

    except websockets.exceptions.WebSocketException as e:
        print(f"WebSocket connection failed: {e}")
        raise
    except Exception as e:
        print(f"Unexpected error: {e}")
        raise


async def stream_audio_from_file(audio_file: str, websocket_url: str) -> None:
    """
    Convenience function to stream a specific audio file to the pipeline.

    Args:
        audio_file: Path to the audio file to stream
        websocket_url: WebSocket URL of the Colab server
    """
    await stream_audio_to_pipeline(websocket_url=websocket_url, audio_file=audio_file)


def run_ivr_client(
    websocket_url: Optional[str] = None,
    audio_file: Optional[str] = None
) -> None:
    """
    Main entry point for running the IVR client.

    Args:
        websocket_url: URL of the Colab WebSocket server
        audio_file: Path to the test audio file
    """
    try:
        asyncio.run(stream_audio_to_pipeline(websocket_url, audio_file))
    except KeyboardInterrupt:
        print("Streaming stopped manually.")
    except FileNotFoundError as e:
        print(f"File error: {e}")
    except Exception as e:
        print(f"Connection failed: {e}")


if __name__ == "__main__":
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    # Run the client
    run_ivr_client()
