"""Add new schema

Revision ID: cb896e9e1284
Revises: 
Create Date: 2026-04-26 20:26:51.498062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb896e9e1284'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_windows_chat_id'), 'context_windows', ['chat_id'], unique=False)
    op.create_index(op.f('ix_context_windows_user_id'), 'context_windows', ['user_id'], unique=False)
    op.drop_table('refusal_decisions')
    op.drop_table('sentinel_runs')
    op.drop_table('sigma_hypotheses')
    op.drop_table('playing_with_neon')
    op.drop_table('boundary_violations')
    op.drop_index(op.f('idx_admin_requests_status'), table_name='admin_requests')
    op.drop_index(op.f('idx_admin_requests_user_id'), table_name='admin_requests')
    op.drop_table('admin_requests')
    op.add_column('chats', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chats_session_id'), 'chats', ['session_id'], unique=False)
    op.add_column('messages', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.drop_index(op.f('idx_uploaded_assets_session'), table_name='uploaded_assets')
    op.add_column('users', sa.Column('clerk_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_column('users', 'clerk_user_id')
    op.create_index(op.f('idx_uploaded_assets_session'), 'uploaded_assets', ['session_id'], unique=False)
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_column('messages', 'metadata_json')
    op.drop_column('messages', 'user_id')
    op.drop_index(op.f('ix_chats_session_id'), table_name='chats')
    op.drop_column('chats', 'session_id')
    op.create_table('admin_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])", name=op.f('status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_requests_pkey'))
    )
    op.create_index(op.f('idx_admin_requests_user_id'), 'admin_requests', ['user_id'], unique=False)
    op.create_index(op.f('idx_admin_requests_status'), 'admin_requests', ['status'], unique=False)
    op.create_table('boundary_violations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('claim_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('severity_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('severity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grounding_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('required_grounding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_grounding', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('human_review_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('boundary_violations_pkey'))
    )
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.create_table('sigma_hypotheses',
    sa.Column('hypothesis_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('model_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('statement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('hypothesis_id', name=op.f('sigma_hypotheses_pkey'))
    )
    op.create_table('sentinel_runs',
    sa.Column('run_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('input_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('run_id', name=op.f('sentinel_runs_pkey'))
    )
    op.create_table('refusal_decisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refused', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('refusal_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('boundary_severity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('severity_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('violation_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('refusal_decisions_pkey'))
    )
    op.drop_index(op.f('ix_context_windows_user_id'), table_name='context_windows')
    op.drop_index(op.f('ix_context_windows_chat_id'), table_name='context_windows')
    op.drop_table('context_windows')
    # ### end Alembic commands ###
