version: "3.9"

services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:latest
    container_name: supertokens-core
    restart: unless-stopped
    ports:
      - "3567:3567"
    environment:
      POSTGRESQL_CONNECTION_URI: ${SUPERTOKENS_POSTGRESQL_CONNECTION_URI}
      API_KEYS: ${SUPERTOKENS_API_KEY}
      DISABLE_TELEMETRY: "true"
